name: Steam Deploy 🎮

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  steam-deploy:
    name: Steam Deploy
    uses: void2610/unity-coding-standards/.github/workflows/steam-deploy-self-hosted.yml@main
    with:
      unity-version: 6000.3.10f1
      runner-labels: '["self-hosted","macOS"]'
      windows-execute-method: CiBuild.BuildWindows
      mac-execute-method: CiBuild.BuildMac
      release-branch: test
    secrets:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
      STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
